#!/bin/sh
#
# Automatically format and mount persistent storage
#


start() {
  echo -n "Automounting: "
  local magic="dhyve, please format-me"
  vgchange -ay

  if [ ! -b "/dev/docker/user" ]; then
    local unpartitioned=$(fdisk -l | grep "doesn't contain a valid partition table" | head -n 1 | sed 's/Disk \(.*\) doesn.*/\1/')

    if [ -n "$unpartitioned" ]; then
      local header=$(dd if=$unpartitioned bs=1 count=${#magic} 2>/dev/null)

      if [ "$header" == "$magic" ]; then
        dd if=$unpartitioned of=/userdata.tar bs=1 count=4096 2>/dev/null
        (echo n; echo p; echo 1; echo ;echo ; echo t; echo 8e; echo w) | fdisk $unpartitioned

        local timer=0
        while [ "$timer" -lt 10 -a \(! -b "${unpartitioned}1" \)]; do
          timer=$((timer + 1))
          sleep 1
        done

        pvcreate "${unpartitioned}1"
        vgcreate docker "${unpartitioned}1"
        lvcreate -L 1G -n swap docker
        mkswap "/dev/docker/swap"
        swapon "/dev/docker/swap"

        lvcreate -L 1G -n user docker
        mkfs.xfs /dev/docker/user

        lvcreate -l 10%VG -n metadata docker
        lvcreate -l 100%VG -n data docker
      fi
    fi
  fi

  if [ -b "/dev/docker/user" ]; then
    mkdir -p /mnt/user
    mount /dev/docker/user /mnt/user 2>/dev/null
    mkdir -p /mnt/user/var/lib/docker
    mkdir -p /mnt/user/etc
    mkdir -p /mnt/user/work/etc

    mount -t overlay overlay -o lowerdir=/etc,upperdir=/mnt/user/etc,workdir=/mnt/user/work/etc /etc
    ln -sf /mnt/user/var/lib/docker /var/lib/docker

    if [ -e "/userdata.tar" ]; then
      mv /userdata.tar /mnt/user/
    fi

    if [ -e "/mnt/user/userdata.tar" ]; then
      tar xf /mnt/user/userdata.tar -C /home/docker >/var/log/userdata.log 2>&1
      chown -R docker:docker /home/docker
      chmod 700 /home/docker/.ssh
      chmod 600 /home/docker/.ssh/authorized_keys
      rm -f '/home/docker/dhyve, please format-me'
    fi
  fi

  if [ -b "/dev/docker/swap" ]; then
    swapon /dev/docker/swap
  fi

  echo "OK"
}

stop() {
  echo ""
}

restart() {
  echo ""
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
