#!/bin/sh
#
# Automatically mount NFS share from host system
#

start() {
  echo -n "Mounting NFS share:"
  local share=$(cat /proc/cmdline | sed -n 's/^.*share=\([^ ]\+\).*$/\1/p')
  if [ -z "$share" ]; then
    share="/Users"
  fi

  local timer=0
  local gateway=""
  while [ "$timer" -lt 10 -a -z "$gateway" ]; do
    gateway=$(ip route get 8.8.8.8 | awk 'NR==1 {print $3}')
    timer=$((timer + 1))
    sleep 1
  done

  if [ -n "$gateway" ]; then
    mkdir -p "$share"
    mount ${gateway}:"$share" "$share" -o rw,async,noatime,rsize=32768,wsize=32768,proto=tcp
    echo "OK"
  else
    echo "FAIL"
  fi
}

stop() {
  local share=$(cat /proc/cmdline | sed -n 's/^.*share=\([^ ]\+\).*$/\1/p')
  if [ -z "$share" ]; then
    share="/Users"
  fi

  if [ -d "$share" ]; then
    umount -f "$share"
  fi
}

restart() {
  echo ""
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
