#!/bin/sh
#
# Start the dlite rpc service
#

start() {
    echo -n "Starting dlite rpc service: "
    start-stop-daemon -S -q -m -b -p /var/run/dlitesvc.pid --exec /usr/sbin/dlitesvc -- daemon 2>&1 >/var/log/dlitesvc.log
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    echo -n "Stopping dlite rpc service: "
    start-stop-daemon -K -q -p /var/run/dlitesvc.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
