#!/bin/sh
#
# Configures sysctl
#

start() {
    echo -n "Configuring sysctl: "
    umask 077
    sysctl -p /etc/sysctl.conf >/dev/null 2>&1
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
  echo ""
}
restart() {
  echo ""
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
