#!/bin/sh
#
# Starts docker
#

# Allow a few customizations from a config file
test -r /etc/default/docker && . /etc/default/docker
CGROUPS="perf_event net_cls freezer devices blkio memory cpuacct cpuset cpu"

start() {
    local docker_version=$(cat /proc/cmdline | sed -n 's/^.*docker_version=\([^ ]\+\).*$/\1/p')
    local installed_docker=$(/usr/bin/docker --version 2>/dev/null | sed -n 's/^.*version \([^, ]\+\).*$/\1/p')
    if [ ! -x /usr/bin/docker -o "$installed_docker" != "$docker_version" ]; then
      wget -qO /tmp/docker.tgz https://get.docker.io/builds/Linux/x86_64/docker-${docker_version}.tgz
      tar -C /tmp -xf /tmp/docker.tgz
      if [ -d "/tmp/docker" ]; then
        mv /tmp/docker/* /usr/bin/
      else
        mv /tmp/usr/local/bin/docker /usr/bin/
      fi
    fi

    export DOCKER_RAMDISK=true
    local extra_args=$(cat /proc/cmdline | sed -n 's/^.*docker_extra=\(.\+\)$/\1/p')
    DOCKER_ARGS="$DOCKER_ARGS --ip=$(ifconfig eth0 | awk '/inet addr/{print substr($2,6)}') ${extra_args}"
    echo -n "Starting docker: "
    umask 077
    ulimit -n 1048576
    ulimit -p 1048576

    mkdir -p /sys/fs/cgroup
    mount -t tmpfs none /sys/fs/cgroup
    for i in $CGROUPS; do
      mkdir -p /sys/fs/cgroup/$i
      mount -t cgroup -o $i none /sys/fs/cgroup/$i
    done

    start-stop-daemon --start --quiet --background --pidfile /var/run/docker.pid \
        --startas /bin/sh -- -c "exec /usr/bin/docker daemon $DOCKER_ARGS >/var/log/docker.log 2>&1"
    if [ $? = 0 ]; then
      echo "OK"
      /usr/sbin/dlitesvc status ready 2>&1 >/dev/null
    else
      echo "FAIL"
    fi
}
stop() {
    echo -n "Stopping docker: "
    start-stop-daemon -K -q -p /var/run/docker.pid
    res=$?
    for i in $CGROUPS; do
      umount /sys/fs/cgroup/$i
    done
    umount /sys/fs/cgroup

    [ $res = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
